### ISSUE TITLE
GUEK and GAK for Stromnetze Graz/Austria

### ISSUE THREAD

**Issue by nischelwitzer** [hansij66/dsmr2mqtt#5]
Hi,

There is a "dsmr50_Stromnetz_Graz_Austria.py" so i think it should work also 
in Graz with the **Sagemcom T210-D-r**

Where i have to enter the two codes (got from https://portal.e-netze.at/anschlussobjektdaten ) in your files?
- **GAK** (Global authentification key)
- **GUEK** (Global unicast encryption key)

Thanks, Alex

**Comment by hansij66** [comment]
Apologies for late reply. In Netherlands we don’t need encryption or authenthication. Hence, I have not implemented this, and also no clue how to do thisBest regards,Hans On 26 Jul 2023, at 09:10, Alexander Nischelwitzer ***@***.***> wrote:﻿
Hi,
There is a "dsmr50_Stromnetz_Graz_Austria.py" so i think it should work also
in Graz with the Sagemcom T210-D-r
Where i have to enter the two codes (got from https://portal.e-netze.at/anschlussobjektdaten ) in your files?

GAK (Global authentification key)
GUEK (Global unicast encryption key)

Thanks, Alex

**Comment by hansij66** [comment]
I don't have enough technical information to implement GAK and GUEK
